/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as MomoRouteImport } from './routes/momo'
import { Route as MeRouteImport } from './routes/me'
import { Route as JuliaRouteImport } from './routes/julia'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExperiencesRouteRouteImport } from './routes/experiences/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesDtrhRouteImport } from './routes/experiences/dtrh'

const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const MomoRoute = MomoRouteImport.update({
  id: '/momo',
  path: '/momo',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const JuliaRoute = JuliaRouteImport.update({
  id: '/julia',
  path: '/julia',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRouteRoute = ExperiencesRouteRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesDtrhRoute = ExperiencesDtrhRouteImport.update({
  id: '/dtrh',
  path: '/dtrh',
  getParentRoute: () => ExperiencesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/julia': typeof JuliaRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
  '/experiences/dtrh': typeof ExperiencesDtrhRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/julia': typeof JuliaRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
  '/experiences/dtrh': typeof ExperiencesDtrhRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/julia': typeof JuliaRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
  '/experiences/dtrh': typeof ExperiencesDtrhRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiences'
    | '/home'
    | '/julia'
    | '/me'
    | '/momo'
    | '/thoughts'
    | '/experiences/dtrh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiences'
    | '/home'
    | '/julia'
    | '/me'
    | '/momo'
    | '/thoughts'
    | '/experiences/dtrh'
  id:
    | '__root__'
    | '/'
    | '/experiences'
    | '/home'
    | '/julia'
    | '/me'
    | '/momo'
    | '/thoughts'
    | '/experiences/dtrh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesRouteRoute: typeof ExperiencesRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  JuliaRoute: typeof JuliaRoute
  MeRoute: typeof MeRoute
  MomoRoute: typeof MomoRoute
  ThoughtsRoute: typeof ThoughtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/momo': {
      id: '/momo'
      path: '/momo'
      fullPath: '/momo'
      preLoaderRoute: typeof MomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/julia': {
      id: '/julia'
      path: '/julia'
      fullPath: '/julia'
      preLoaderRoute: typeof JuliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/dtrh': {
      id: '/experiences/dtrh'
      path: '/dtrh'
      fullPath: '/experiences/dtrh'
      preLoaderRoute: typeof ExperiencesDtrhRouteImport
      parentRoute: typeof ExperiencesRouteRoute
    }
  }
}

interface ExperiencesRouteRouteChildren {
  ExperiencesDtrhRoute: typeof ExperiencesDtrhRoute
}

const ExperiencesRouteRouteChildren: ExperiencesRouteRouteChildren = {
  ExperiencesDtrhRoute: ExperiencesDtrhRoute,
}

const ExperiencesRouteRouteWithChildren =
  ExperiencesRouteRoute._addFileChildren(ExperiencesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesRouteRoute: ExperiencesRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  JuliaRoute: JuliaRoute,
  MeRoute: MeRoute,
  MomoRoute: MomoRoute,
  ThoughtsRoute: ThoughtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
