/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThoughtsImport } from './routes/thoughts'
import { Route as MomoImport } from './routes/momo'
import { Route as MeImport } from './routes/me'
import { Route as HomeImport } from './routes/home'
import { Route as ExperiencesRouteImport } from './routes/experiences/route'
import { Route as IndexImport } from './routes/index'
import { Route as ExperiencesDtrhImport } from './routes/experiences/dtrh'

// Create/Update Routes

const ThoughtsRoute = ThoughtsImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRoute,
} as any)

const MomoRoute = MomoImport.update({
  id: '/momo',
  path: '/momo',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesRouteRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesDtrhRoute = ExperiencesDtrhImport.update({
  id: '/dtrh',
  path: '/dtrh',
  getParentRoute: () => ExperiencesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/momo': {
      id: '/momo'
      path: '/momo'
      fullPath: '/momo'
      preLoaderRoute: typeof MomoImport
      parentRoute: typeof rootRoute
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsImport
      parentRoute: typeof rootRoute
    }
    '/experiences/dtrh': {
      id: '/experiences/dtrh'
      path: '/dtrh'
      fullPath: '/experiences/dtrh'
      preLoaderRoute: typeof ExperiencesDtrhImport
      parentRoute: typeof ExperiencesRouteImport
    }
  }
}

// Create and export the route tree

interface ExperiencesRouteRouteChildren {
  ExperiencesDtrhRoute: typeof ExperiencesDtrhRoute
}

const ExperiencesRouteRouteChildren: ExperiencesRouteRouteChildren = {
  ExperiencesDtrhRoute: ExperiencesDtrhRoute,
}

const ExperiencesRouteRouteWithChildren =
  ExperiencesRouteRoute._addFileChildren(ExperiencesRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
  '/experiences/dtrh': typeof ExperiencesDtrhRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
  '/experiences/dtrh': typeof ExperiencesDtrhRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
  '/experiences/dtrh': typeof ExperiencesDtrhRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiences'
    | '/home'
    | '/me'
    | '/momo'
    | '/thoughts'
    | '/experiences/dtrh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiences'
    | '/home'
    | '/me'
    | '/momo'
    | '/thoughts'
    | '/experiences/dtrh'
  id:
    | '__root__'
    | '/'
    | '/experiences'
    | '/home'
    | '/me'
    | '/momo'
    | '/thoughts'
    | '/experiences/dtrh'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesRouteRoute: typeof ExperiencesRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  MeRoute: typeof MeRoute
  MomoRoute: typeof MomoRoute
  ThoughtsRoute: typeof ThoughtsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesRouteRoute: ExperiencesRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  MeRoute: MeRoute,
  MomoRoute: MomoRoute,
  ThoughtsRoute: ThoughtsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/experiences",
        "/home",
        "/me",
        "/momo",
        "/thoughts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/experiences": {
      "filePath": "experiences/route.tsx",
      "children": [
        "/experiences/dtrh"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/me": {
      "filePath": "me.tsx"
    },
    "/momo": {
      "filePath": "momo.tsx"
    },
    "/thoughts": {
      "filePath": "thoughts.tsx"
    },
    "/experiences/dtrh": {
      "filePath": "experiences/dtrh.tsx",
      "parent": "/experiences"
    }
  }
}
ROUTE_MANIFEST_END */
