/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThoughtsImport } from './routes/thoughts'
import { Route as MomoImport } from './routes/momo'
import { Route as MeImport } from './routes/me'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ThoughtsRoute = ThoughtsImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRoute,
} as any)

const MomoRoute = MomoImport.update({
  id: '/momo',
  path: '/momo',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/momo': {
      id: '/momo'
      path: '/momo'
      fullPath: '/momo'
      preLoaderRoute: typeof MomoImport
      parentRoute: typeof rootRoute
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/momo': typeof MomoRoute
  '/thoughts': typeof ThoughtsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/me' | '/momo' | '/thoughts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/me' | '/momo' | '/thoughts'
  id: '__root__' | '/' | '/home' | '/me' | '/momo' | '/thoughts'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  MeRoute: typeof MeRoute
  MomoRoute: typeof MomoRoute
  ThoughtsRoute: typeof ThoughtsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  MeRoute: MeRoute,
  MomoRoute: MomoRoute,
  ThoughtsRoute: ThoughtsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/me",
        "/momo",
        "/thoughts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/me": {
      "filePath": "me.tsx"
    },
    "/momo": {
      "filePath": "momo.tsx"
    },
    "/thoughts": {
      "filePath": "thoughts.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
